### ISSUE TITLE
Jammer Core 2.0 Roadmap

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#2089]
Once we finish the "great code cleanup and triage", the next step is to split JammerCore into multiple modular components.

The components are as follows:

* [ ] The code in `/src/shrub/js` becomes the [JammerSDK](https://github.com/JammerCore/JammerSDK)
  * A proper JavaScript module usable for both the browser and in Node/Deno apps
* [ ] The rest of the JavaScript code becomes [JammerApp](https://github.com/JammerCore/JammerApp)
  * JammerSDK is included as a GIT remote
* [ ] Ludum Dare specifics (logo, sponsors) become a JammerApp template. That goes in the [jam.ludumdare.com](https://github.com/LudumDare/jam.ludumdare.com) repo
   * `jam.ludumdare.com` will replace `ldjam.com` once it is ready
* [ ] The PHP side of the homepages (`/public-ludumdare.com`) become [JammerHome](https://github.com/JammerCore/JammerHome)
  * These pages are dumb.
  * They have access the database, but frankly they don't need it. They don't need authentication either.
  * This should change into a new project that queries the public API and caches it
    * The cached data can be returned and used as a "starting point" for applications while data is streaming in
    * With access to the node data, it can also emit metadata used for indexing by spiders, crawlers, and search engines
      * Rant: Oh man, this has been EXTREMELY frustrating lately. I was trying to lookup data on our website, but because we lack search and we aren't indexable, I couldn't find anything.
  * This could be outright replaced by a Node or Deno app using JammerSDK, or a new app written in Rust
    * The trick is we need some in-memory storage solution that's as good, if not better then PHP's APCu
    * APCu uses CPU concurrency primitives to ensure parallel threads aren't stomping over the same data, but it lacks something akin to MySQL's BEGIN and END statements to intelligently lock, read, write, and unlock batches
    * By design, PHP scripts that fulfill requests are constantly created and killed. PHP scripts are rarely long lived.
    * An asynchronous event driven application that is "long lived" could do the same job, so long as it's able to lock and unlock
* [ ] The leaves just the backend API and `shrub/src`. This becomes [JammerAPI](https://github.com/JammerCore/JammerAPI)

Once JammerSDK, JammerApp, JammerAPI, and JammerHome move out and go live, this project can be closed. If applicable, any outstanding issues can be carried over.

The name "Jammer Core" will refer to the group of projects that power Ludum Dare and its related services.
